ml_conf = {
    "CoNLL": "Conference on Computational Natural Language Learning",
    "ICML": "International Conference on Machine Learning",
    "NeurIPS": "Neural Information Processing Systems",
    "ECML-PKDD": "European conference on Machine Learning and Principles of Data Mining and Knowledge Discovery",
    "ICONIP": "International Conference on Neural Information Processing",
    "IJCNN": "International Joint Conference on Neural Network",
    "PPSN": "Parallel Problem Solving from Nature",
}

ai_conf = {
    "AAAI": "National Conference on Artificial Intelligence",
    "AAMAS": "Adaptive Agents and Multi-Agents Systems",
    "ACL": "Meeting of the Association for Computational Linguistics",
    "AISTATS": "International Conference on Artificial Intelligence and Statistics",
    "COLING": "International Conference on Computational Linguistics",
    "COLT": "Conference on Learning Theory",
    "EACL": "Conference of the European Chapter of the Association for Computational Linguistics",
    "EMNLP": "Empirical Methods in Natural Language Processing",
    "ICRA": "International Conference on Robotics and Automation",
    "IJCAI": "International Joint Conference on Artificial Intelligence",
    "IJCNLP": "International Joint Conference on Natural Language Processing",
    "NAACL": "North American Chapter of the Association for Computational Linguistics",
    "UAI": "Uncertainty in Artificial Intelligence",
    "CP": "Principles and Practice of Constraint Programming",
    "ECAI": "European Conference on Artificial Intelligence",
    "ICAPS": "International Conference on Automated Planning and Scheduling",
    "ICCBR": "International Conference on Case-Based Reasoning",
    "KR": "Principles of Knowledge Representation and Reasoning",
    "GECCO": "Genetic and Evolutionary Computation Conference",
    "FUZZ-IEEE": "IEEE International Conference on Fuzzy Systems",
    "CADE": "Conference on Automated Deduction",
    "ACCS": "Conference Cognitive Science",
    "EC": "Economics and Computation",
    "FOGA": "Foundations of Genetic Algorithms",
    "ICARCV": "International Conference on Control, Automation, Robotics and Vision",
    "IJCAR": "International Joint Conference on Automated Reasoning",
    "IROS": "Intelligent Robots and Systems",
    "ISR": "International Symposium on Robotics",
    "INTERSPEECH": "Conference of the International Speech Communication Association",
    "LPNMR": "Logic Programming and Non-Monotonic Reasoning",
    "SAT": "Theory and Applications of Satisfiability Testing",
}

vision_conf = {
    "CVPR": "Computer Vision and Pattern Recognition",
    "ICCV": "International Conference on Computer Vision",
    "ECCV": "European Conference on Computer Vision",
    "ACCV": "Asian Conference on Computer Vision",
    "CPM": "Combinatorial Pattern Matching",
    "WACV": "Workshop on Applications of Computer Vision",
    "ACMMM": "ACM Multimedia",
}
